from api_search import search_openalex,search_crossref
from utils import remove_duplicates_and_convert_doi,get_latest_json,save_results_to_json, convert_latest_json_to_gdoc,get_latest_json
import datetime
convert_latest_json_to_gdoc()
